### ISSUE TITLE
Bazel build doesn't work on Mac OS 10.13.2

### ISSUE THREAD

**Issue by vertix** [google/glog#282]
In project directory, run `bazel build --verbose_failures  :glog`

```
INFO: Analysed target //:glog (0 packages loaded).
INFO: Found 1 target...
ERROR: /Users/vertix/Documents/glog/BUILD:5:1: C++ compilation of rule '//:glog' failed (Exit 1): wrapped_clang failed: error executing command
  (cd /private/var/tmp/_bazel_vertix/6186e00fb72db411bd56ae56577e26e2/execroot/__main__ && \
  exec env - \
    APPLE_SDK_PLATFORM='' \
    APPLE_SDK_VERSION_OVERRIDE='' \
    PATH=/Users/vertix/Downloads/google-cloud-sdk/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/go/bin:/opt/X11/bin \
    TMPDIR=/var/folders/30/bcm7s97933s8ljwbr1jwjpy40000gn/T/ \
    XCODE_VERSION_OVERRIDE=9.2.0 \
  external/local_config_cc/wrapped_clang '-D_FORTIFY_SOURCE=1' -fstack-protector -fcolor-diagnostics -Wall -Wthread-safety -Wself-assign -fno-omit-frame-pointer -O0 -DDEBUG '-std=c++11' -iquote . -iquote bazel-out/darwin-fastbuild/genfiles -iquote external/com_github_gflags_gflags -iquote bazel-out/darwin-fastbuild/genfiles/external/com_github_gflags_gflags -iquote external/bazel_tools -iquote bazel-out/darwin-fastbuild/genfiles/external/bazel_tools -Ibazel-out/darwin-fastbuild/bin/_virtual_includes/glog -isystem external/com_github_gflags_gflags/include -isystem bazel-out/darwin-fastbuild/genfiles/external/com_github_gflags_gflags/include -isystem external/bazel_tools/tools/cpp/gcc3 -MD -MF bazel-out/darwin-fastbuild/bin/_objs/glog/src/vlog_is_on.d '-frandom-seed=bazel-out/darwin-fastbuild/bin/_objs/glog/src/vlog_is_on.o' '-isysroot __BAZEL_XCODE_SDKROOT__' -Wno-sign-compare -Wno-unused-function -Wno-unused-local-typedefs -Wno-unused-variable '-D_START_GOOGLE_NAMESPACE_=namespace google {' '-D_END_GOOGLE_NAMESPACE_=}' '-DGOOGLE_NAMESPACE=google' -DHAVE_PTHREAD -DHAVE_SYS_UTSNAME_H -DHAVE_SYS_SYSCALL_H -DHAVE_SYS_TIME_H -DHAVE_STDINT_H -DHAVE_STRING_H -DHAVE_SIGACTION -DHAVE_PREAD -Ibazel-out/darwin-fastbuild/genfiles/glog_internal -DHAVE_LIB_GFLAGS -no-canonical-prefixes -Wno-builtin-macro-redefined '-D__DATE__="redacted"' '-D__TIMESTAMP__="redacted"' '-D__TIME__="redacted"' -c src/vlog_is_on.cc -o bazel-out/darwin-fastbuild/bin/_objs/glog/src/vlog_is_on.o)

Use --sandbox_debug to see verbose messages from the sandbox
clang: error: no such file or directory: 'google'
clang: error: no such file or directory: '{'
Target //:glog failed to build
```

`bazel version` reports:
```
Build label: 0.9.0-homebrew
Build target: bazel-out/darwin-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Sun Jul 12 12:24:01 +49936 (1513677414241)
Build timestamp: 1513677414241
Build timestamp as int: 1513677414241
```

**Comment by drigz** [comment]
This is due to https://github.com/bazelbuild/bazel/issues/3979.

We could work around it by writing the #define into config.h, although it's not clear what the best way to do this is. Options:
- an even bigger `sed` invocation than [gen.sh](https://github.com/google/glog/blob/028d37889a1e80e8a07da1b8945ac706259e5fd8/bazel/glog.bzl#L100).
- add a dependency on [cc_fix_config](https://github.com/antonovvk/bazel_rules/blob/98ddd7e4f7c63ea0868f08bcc228463dac2f9f12/examples/config/BUILD#L48)
- add a `config.h.bazel` that we could just copy across to `config.h`

The `config.h.bazel` option would be easiest, but we'd have to remove the `namespace` option for `glog_library`. @qzmfranklin, is there a reason you added the `namespace` option originally? The namespace appears to be [hardcoded as `google` in gen.sh](https://github.com/google/glog/blob/028d37889a1e80e8a07da1b8945ac706259e5fd8/bazel/glog.bzl#L100) so maybe we need to remove or fix it.

@sergiud, feel free to assign future Bazel issues to me.

**Comment by sergiud** [comment]
@drigz Got it!

**Comment by qzmfranklin** [comment]
Hi @drigz ,

Just saw this. Re 'why add the namespace originally':

I wanted to make it possible for users to choose their own namespace for `glog`. I have seen people using both `google::glog` and `glog:glog` (at for example, microsoft) before. Allowing to the users to choose a non-google namespace makes it easier for them to adopt `glog`.

That's all I had.

**Comment by qzmfranklin** [comment]
@drigz ,

The namespace, as hardcoded in `gen.sh`, I believe is an oversight and should be fixed. I intended to make it possible to use any namespace of the user's choice but did not test thoroughly on this.
