### ISSUE TITLE
glog bazel rules seem to be broken

### ISSUE THREAD

**Issue by nate-meta** [google/glog#289]
I've added glog in my Bazel WORKSPACE as follows:
```
git_repository(
    name = "com_github_glog_glog",
    commit = "3106945d8d3322e5cbd5658d482c9ffed2d892c0",
    remote = "https://github.com/google/glog.git",
)

bind(
    name = "glog",
    actual = "@com_github_glog_glog//:glog",
)
```

When I run 'bazel build //external:glog' it builds fine, however, if I try to add stl_logging.h as a dependency of a class, I get the following error:
```
bazel-out/darwin-fastbuild/bin/external/com_github_glog_glog/_virtual_includes/glog/glog/stl_logging.h:50:6: error: invalid token at start of a preprocessor expression
#if !@ac_cv_cxx_using_operator@
     ^
```

Looking at the generated file from the bazel rule under glog.bzl it looks like there is missing the string replacement to remove `ac_cv_cxx_using_operator`.

Next I tried to directly add the project under a third_party/glog/ directory in my repo to try to fix this locally in order to test, however, there seems to be an issue with the output of of the config_h rule not being found under `copts = [..., '-I%s/glog_internal' % gendir,...]`.

Thoughts on how to resolve either of these issues?

**Comment by drigz** [comment]
@nate-meta, thanks for the report! I'll look into the broken stl_logging.h, but in the short term, you should be able to use glog/logging.h ([example](https://github.com/google/glog/blob/master/bazel/example/main.cc)).

Regarding the second issue, vendoring dependencies can be tough as you noticed. I'd recommend checking out glog elsewhere (eg `~/git/glog`), and using:

`bazel build --override_repository com_github_glog_glog=$HOME/git/glog //my/package:my_binary`

to test your local changes. That's what I do when I need to fix a dependency.

PS. `bind` is not recommended (although lots of projects still use it) - it's better to just depend directly on `@com_google_glog//:glog`.
PPS. I'd suggest calling the repo `com_google_glog`, otherwise you may see a build warning (or even failure) at some point in the future.

**Comment by nate-meta** [comment]
Thanks for the quick fix and the feedback!

bazel build --override_repository - cool stuff!  Thanks for the pointer!

bind() - I saw that comment on the API docs, curious to see how they will deprecate it since its so wildly used.

Repo name - thanks for catching the error!  Doesn't looks like the glog WORKSPACE defines the workspace name so just took a best guess.  Is there a better way to reason on what the workspace name should be if one is not defined?  I would have actually assumed it would be @com_github_google_glog.

**Comment by drigz** [comment]
bind() - you can read more here if you're curious: https://github.com/bazelbuild/bazel/issues/1952

repo name - Google projects on GitHub tend to use `com_google_projectname` as the workspace name - eg protobuf: https://github.com/google/protobuf/blob/6456e5d6462e8c3d21d6afd64420dbd028ea3245/WORKSPACE#L1

But no, there's no unambiguous way to generate a workspace name at the moment.
