### ISSUE TITLE
Get trouble in compiling glog for android!

### ISSUE THREAD

**Issue by CarlLyt** [google/glog#355]
Hello everybody.
before compiling, i successfully installed gflag, so there was no warning when i Configure and  Generate the glog.
(compile env: win10     ndk17    CMake3.12   MinGW)

![test](https://user-images.githubusercontent.com/42412722/44319884-3c9d4680-a471-11e8-939f-9528e56c8a40.png)

then  i was met  errors like this:
D:\Restor\chajian\glog-0.3.5\build>make
[ 44%] Built target glog
[ 55%] Built target utilities_unittest
[ 66%] Built target demangle_unittest
[ 72%] Building CXX object CMakeFiles/logging_unittest.dir/src/logging_unittest.cc.o
D:\Restor\chajian\glog-0.3.5\src\logging_unittest.cc:617:17: error: use of undeclared identifier 'glob'
  const int r = glob(pattern.c_str(), 0, NULL, &g);
                ^
D:\Restor\chajian\glog-0.3.5\src\logging_unittest.cc:622:3: error: use of undeclared identifier 'globfree'
  globfree(&g);
  ^
2 errors generated.
CMakeFiles\logging_unittest.dir\build.make:61: recipe for target 'CMakeFiles/logging_unittest.dir/src/logging_unittest.cc.o' failed
make[2]: *** [CMakeFiles/logging_unittest.dir/src/logging_unittest.cc.o] Error 1
CMakeFiles\Makefile2:1078: recipe for target 'CMakeFiles/logging_unittest.dir/all' failed
make[1]: *** [CMakeFiles/logging_unittest.dir/all] Error 2
Makefile:161: recipe for target 'all' failed
make: *** [all] Error 2

I have no idea with it.
somebody can help me ?

**Comment by iliis** [comment]
If you look into `$ANDROID_NDK/toolchains/llvm/prebuilt/linux-x86_64/sysroot/usr/include/glob.h`, you'll find that at least Android API Level 28 (Android 9, "Pie") is required for `glob()`.

However, this is just the compilation of a unittest that fails due to it's reliance on `glob()`. The library itself doesn't need it. And you don't need those unittests, especially when cross-compiling. So it's enough to just disable `BUILD_TESTING` in your cmake config.
