### ISSUE TITLE
Bazel: building glog with custom version gflags

### ISSUE THREAD

**Issue by levhuan** [google/glog#480]
It is my first time here, and I already read the contribution guideline. So I hope creating an issue is an appropriate step for this discussion. 

I am working on a bazel workspace that needs to import and build both *gflags* and *glog* from source. I would like to build *glog* using the version of *gflags* in my workspace, instead of the one specified in glog `WORKSPACE` file. Hence, would the following change work and be accepted?

```
load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

http_archive(
    name = "com_github_gflags_gflags",
    strip_prefix = "gflags-2.2.2",
    urls = [
        "https://mirror.bazel.build/github.com/gflags/gflags/archive/v2.2.2.tar.gz",
        "https://github.com/gflags/gflags/archive/v2.2.2.tar.gz",
    ],
)
```

to:

```load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")
if "com_github_gflags_gflags" not in native.existing_rules():
    http_archive(
        name = "com_github_gflags_gflags",
        strip_prefix = "gflags-2.2.2",
        urls = [
            "https://mirror.bazel.build/github.com/gflags/gflags/archive/v2.2.2.tar.gz",
            "https://github.com/gflags/gflags/archive/v2.2.2.tar.gz",
        ],
    )
```

**Comment by drigz** [comment]
If I understand correctly, you shouldn't need to change glog to do what you want. Since Bazel ignores the WORKSPACE files of external repositories (see https://github.com/bazelbuild/bazel/issues/1943), adding glog to your WORKSPACE will not add gflags: you'll have to add it yourself. You can add any version that you want, as long as it includes https://github.com/gflags/gflags/commit/57ceb0ecc8bf5c129bf99fa9472b25342daecf9e (2.2.2 is the first release with this commit).

Does that help?

PS: The `if ... not in native.existing_rules():` pattern can't be used directly in the WORKSPACE file ([if statements aren't allowed in BUILD or WORKSPACE files](https://docs.bazel.build/versions/master/build-ref.html#BUILD_files)), but it is useful inside a dependencies macro that is intended to be called from the WORKSPACE to add a group of dependencies. glog doesn't provide a macro like that since it only has one (optional) dependency, so it's easier to let people add gflags to the top-level WORKSPACE themselves.

**Comment by levhuan** [comment]
Thanks for the response @drigz. Close the issue then.
