### ISSUE TITLE
Undefined symbols to build or run Pytorch on macOS

### ISSUE THREAD

**Issue by essandess** [google/glog#660]
Pytorch fails to compile on macOS because of the undefined symbol `google::glog_internal_namespace_::IsGoogleLoggingInitialized()`:

```
:info:build Undefined symbols for architecture x86_64:
:info:build   "google::glog_internal_namespace_::IsGoogleLoggingInitialized()", referenced from:
:info:build       c10::InitCaffeLogging(int*, char**) in Logging.cpp.o
:info:build ld: symbol(s) not found for architecture x86_64
:info:build clang: error: linker command failed with exit code 1 (use -v to see invocation)
```
 
Related:
* https://github.com/google/glog/issues/575
* https://trac.macports.org/ticket/62921

**Comment by sergiud** [comment]
Make sure to use search first. See #125.

**Comment by essandess** [comment]
> Make sure to use search first. See #125.

I'm not familiar enough with the internals of glog or torch's dependence on glog to understand your response. How is this resolved? Are you saying it's an issue with torch? What's the specific resolution?

**Comment by sergiud** [comment]
There is nothing to resolve in glog. PyTorch uses an internal glog symbol which is not part of the API. The corresponding public API function was added to master only recently (#651).

**Comment by xkszltl** [comment]
I believe the issue may be much more wide-spread than you expect.
Although it's technically UB, I won't blame them for using it because it's the only way to reliably init glog for multiple libs.

<img width="1333" alt="image" src="https://user-images.githubusercontent.com/5203025/120226703-48510500-c27a-11eb-813b-cbc814e3cdbf.png">

In glog 0.5.0, there's simply no way around, which can be a major issue for adoption.
Besides, recently I've seen many libs (both open-source and proprietary) hitting the issue on macOS (due the relatively aggressive upgrade of homebrew).

**Comment by sergiud** [comment]
The very first hit in your screenshot shows a clean way to test whether an initialization was performed which works irrespective of glog version. What's wrong with that?

**Comment by xkszltl** [comment]
That only works if you have full control of glog.
A common scenario is, 2 libs both use glog. They cannot tell whether glog is already initialized by anyone else. They cannot even "try-init" because that'll lead to a fatal error and kill the process.

**Comment by sergiud** [comment]
The described scenario doesn't seem to apply to PyTorch.

Regardless, I reject your idea of providing any kind of compatibility to internal symbols as I already made this very clear. The next version of glog will contain the necessary functionality.

I'm locking the discussion due to pointless arguing.
