### ISSUE TITLE
glog clean function slows down program dramatically

### ISSUE THREAD

**Issue by willkk** [google/glog#702]
![1629440133(1)](https://user-images.githubusercontent.com/17777977/130188598-49967c15-ef79-4e0e-867f-04464e515b58.png)

**Comment by sergiud** [comment]
Please explain how you came to this conclusion.

**Comment by willkk** [comment]
The graph can explain itself. 50% time is consumed by glog, and about 40% time is consumed by GetOverdueLogNames. When I disable log clean function, the program qps is much higher.

**Comment by ThePhyscoD** [comment]
Okay where can I login because I can’t really find that I try using Crypto.com link was sent 
I’m really lost here 


Sent from the all new AOL app for iOS


On Friday, August 20, 2021, 3:20 AM, willkk ***@***.***> wrote:




The graph can explain itself. 50% time is consumed by glog, and about 40% time is consumed by GetOverdueLogNames. When I disable log clean function, the program qps is much higher.

**Comment by sergiud** [comment]
The graph is not sufficient since it provides only the relative times. In turn, such measurement do not necessary result in slow downs you are claiming.

Do you have a benchmark that actually shows a measurable slow down? Also, a complete working example to accompany your measurements is missing.

**Comment by willkk** [comment]
So could glog provide some benchmark?

**Comment by sergiud** [comment]
This would be your responsibility since you claim a "dramatical program slow down".

**Comment by willkk** [comment]
thanks so much.
