### ISSUE TITLE
Can't find glog/logging.h for CMAKE add_library

### ISSUE THREAD

**Issue by skyw** [google/glog#703]
It works fine for executables, i.e.
```cmake
add_subdirectory(third_party/glog)
add_executable (myapp main.cpp)
target_link_libraries (myapp glog::glog)
```
But the following doesn't work
```cmake
add_subdirectory(third_party/glog)
add_library (mylib lib.cpp)
target_link_libraries (mylib glog::glog)
```

it fails with can't find `glog/logging.h`

Played with some include_directories, but can't make it work

**Comment by sergiud** [comment]
Glog does not differentiate between executable and library targets. Therefore the problem is likely in your setup. Given the provided problem description, I also recommend you to consult the CMake documentation for the `target_link_libraries` command and associated signatures to eliminate possible incorrect usage which ultimately prohibits propagation of include directories.
