### ISSUE TITLE
Compile Error with MSVC and std::min

### ISSUE THREAD

**Issue by Fettpet** [google/glog#821]
Hello,

The following code example does not compile. I use the MSVC\14.29.30133 compiler. 

main.cpp
```
#include <glog/logging.h>
#include <algorithm>

int main()
{
   LOG(INFO) << std::min(1, 3);
   return 0;
}
```

CMakeLists.txt
```
cmake_minimum_required(VERSION 3.5)

project(WindowsExample LANGUAGES CXX)

set(CMAKE_CXX_STANDARD 17)
set(CMAKE_CXX_STANDARD_REQUIRED ON)

add_subdirectory(third_party/glog)

add_executable(WindowsExample main.cpp)

target_link_libraries(WindowsExample glog)
```

The problem with this setup is the include of `windows.h`. It contain macros for min and max. Defining `NOMINMAX` before the include of glog/logging.h solves the problem. 

If I define `NOMINMAX` before the include of windows inside the [logging.h.in](https://github.com/google/glog/blob/master/src/glog/logging.h.in#L95), the example above compiles as expected. 

What I am not aware of, is it possible to move the include of windows.h and the coressponding implementation into the cc file? This would solve this and similar issues.

**Comment by sergiud** [comment]
There's no way around defining `NOMINMAX`.

**Comment by RippeR37** [comment]
@sergiud shouldn't this be done inside `glog` though? As it is right now, users/consumers of glog can easily trigger strange compilation errors just by including `glog/logging.h` in specific files, or when upgrading glog from older versions. If glog does not depend on the macros being set-up, it should not leak them, especially quietly.

Some places like `glog/src/base/mutex.h` already do prevent leaking it (albeit still leaks changes to the user's code by leaking "NOMINMAX" macro if it wasn't set, which could potentially break someone's project as well) but not all of them (`windows/dirent.h`, `windows/dirent.h`).

**Comment by sergiud** [comment]
No, definitely not. The default behavior when including `windows.h` is that the header defines `min`/`max` as macros. Therefore, a library cannot be responsible for preventing such definitions since consumers may rely on this behavior. This is also the reason why the macros are defined unless suppressed using `NOMINMAX`.

Preventing the use of `windows.h` in headers is certainly a good idea and you are welcome to submit a PR with the corresponding modifications. However, realistically I don't see this happening because other `windows.h` definitions are used in glog headers.
