### ISSUE TITLE
symbolize_test fails on Bazel CI (Windows only)

### ISSUE THREAD

**Issue by Wyverald** [google/glog#859]
Example breakage: https://buildkite.com/bazel/google-logging/builds/2911#01831a72-99a7-4d0a-a1a6-4761066ca927

This has been consistently failing, with both HEAD Bazel and latest release Bazel (5.3.0).

**Comment by drigz** [comment]
Thanks for the report, and let me know if there's something I should do to opt-in to automated notifications of breakage on master. I don't send PRs regularly enough to see the breakage there.

- last green: [build 2894](https://buildkite.com/bazel/google-logging/builds/2894#0182c2de-b916-4e0c-83a5-d02f2ab9ba84) 22nd August with bazel 5.2.0 at [b70ea80](https://github.com/google/glog/commit/b70ea80433c2a8f20b832be97b90f1f82b0d29e9)
- first red: [build 2895](https://buildkite.com/bazel/google-logging/builds/2895#0182c819-b174-4f07-ad1b-1c899e8c75db) 23rd August with bazel 5.2.0 at [b70ea80](https://github.com/google/glog/commit/b70ea80433c2a8f20b832be97b90f1f82b0d29e9)

Hard to guess what might have changed to cause this. Test artifacts contain:

```
Executing tests from //:symbolize_test
-----------------------------------------------------------------------------
F20220908 00:14:51.232890  3688 symbolize_unittest.cc:431] Check failed: symbol != NULL 
*** Check failure stack trace: ***
    @   00007FF7A7B1B9BA  ?Fail@LogMessage@google@@SAXXZ
    @   00007FF7A7B1B8D0  ?SendToLog@LogMessage@google@@QEAAXXZ
    @   00007FF7A7B1B0B0  ?Flush@LogMessage@google@@QEAAXXZ
    @   00007FF7A7B1CC6C  ??1LogMessageFatal@google@@QEAA@XZ
    @   00007FF7A7B14074  (unknown)
    @   00007FF7A7B1417F  (unknown)
    @   00007FF7A7B4CFF0  ?InstallFailureWriter@google@@YAXP6AXPEBD_K@Z@Z
    @   00007FFE37EB7974  BaseThreadInitThunk
    @   00007FFE3A56A2F1  RtlUserThreadStart
```

The last green run says `//:symbolize_test                                               (cached) PASSED in 0.2s` so I guess it's theoretically possible that the cache was poisoned with a green result - I'm very surprised that test caching is enabled for the daily runs, I wonder if that's standard practice on Bazel CI? I don't however see any obvious change to the cache keys etc that would have invalidated the previous cache...

For now I'll just look into disabling the test as I don't have easy access to a Windows environment to investigate.

**Comment by meteorcloudy** [comment]
Indeed it was a cache issue: I figured out a way to run the build without remote cache, and it passed: https://buildkite.com/bazel/google-logging/builds/2916#01833215-4967-4864-b7c8-c63b5e39d736

>  I'm very surprised that test caching is enabled for the daily runs, I wonder if that's standard practice on Bazel CI?

Actually, yes, we enable remote cache for `test_targets` in postsubmit, but not for `build_targets`. We probably should disable remote cache by default for postsubmit..

**Comment by drigz** [comment]
Interesting, thank you for testing that! I guess the test could be flaky at HEAD, such that the same test binary (since build caching is disabled, I assume that the test binary is reproducible, enabling the test cache to cache the red/green results) may fail or succeed, and we were unlucky enough to see three consecutive failures in build 2895, which were cached until you bumped the cache key.

That said, I actually can't explain why it passed after changing the key in [#2916](https://buildkite.com/bazel/google-logging/builds/2916#01833215-4967-4864-b7c8-c63b5e39d736), as if I set --runs_per_test=30 [#2921](https://buildkite.com/bazel/google-logging/builds/2921) I see:

```
//:symbolize_test     FAILED in 90 out of 90 in 32.5s
  Stats over 90 runs: max = 32.5s, min = 0.0s, avg = 0.9s, dev = 4.7s
```

Maybe it depends on which test runner is used? Is there a test matrix anywhere that would let me disable test caching and see which runners see failures/passes?
