### ISSUE TITLE
Flag --incompatible_enable_cc_toolchain_resolution will break Google Logging in Bazel 7.0

### ISSUE THREAD

**Issue by keertk** [google/glog#876]
Incompatible flag `--incompatible_enable_cc_toolchain_resolution` will be enabled by default in the next major release (Bazel 7.0), thus breaking Google Logging. Please migrate to fix this and unblock the flip of this flag.

The flag is documented here: https://github.com/bazelbuild/bazel/issues/7260

Please check the following CI builds for build and test results:

- [Windows, Clang, OpenJDK 11](https://buildkite.com/bazel/bazelisk-plus-incompatible-flags/builds/1339#018497b7-aa0d-448d-8747-216101a78eb8)

Never heard of incompatible flags before? We have [documentation](https://docs.bazel.build/versions/master/backward-compatibility.html) that explains everything.
If you have any questions, please file an issue in https://github.com/bazelbuild/continuous-integration.

**Comment by drigz** [comment]
@comius Are there any migration instructions for replacing `--compiler` on Windows? I "just" want to test building with both clang and MSVC, although it's not clear if this is possible. In September, you wrote:

> Different compilers on Window are not yet supported with CC toolchain resolution.

and I can't see anything on https://github.com/bazelbuild/bazel/issues/7260 to suggest that that has changed. Is that the right place to look? Thanks in advance!

**Comment by comius** [comment]
> @comius Are there any migration instructions for replacing `--compiler` on Windows? I "just" want to test building with both clang and MSVC, although it's not clear if this is possible. 

The plan is most likely for `--compiler` flag to remain as is. There are use cases also on Linux where a different compiler needs to be selected regardless of the platform in use.

> In September, you wrote:
> 
> > Different compilers on Window are not yet supported with CC toolchain resolution.
> 
> and I can't see anything on [bazelbuild/bazel#7260](https://github.com/bazelbuild/bazel/issues/7260) to suggest that that has changed. Is that the right place to look? Thanks in advance!

That's true - I haven't touched Windows yet. That issue is the right place to look.

Toolchain configuration happens in https://github.com/bazelbuild/bazel/blob/master/tools/cpp/windows_cc_configure.bzl and other files/templates in that directory. I see there is support for different compilers (also on Windows), but it's done with constraints. 

I need some further investigation to figure out if we should keep constraints or use `--compiler` flag.
