### ISSUE TITLE
Bazel CI failing

### ISSUE THREAD

**Issue by sergiud** [google/glog#961]
Bazel CI MSVC Clang builds are failing. This looks like a Bazel issue.

@drigz Any chance you could take a look?

**Comment by drigz** [comment]
Hey, sorry, I have no bandwidth to look at this in the next couple of weeks, and no experience with MSVC builds. If it's blocking something, maybe we could try asking skeptic-monkey (who added it originally) or bqhuyy (as they sent a related PR recently).

**Comment by sergiud** [comment]
No worries, thanks. The build started failing only recently and it is not clear to me why is that. However, I suspect a Bazel update.

cc @skeptic-monkey

**Comment by skeptic-monkey** [comment]
I guess you're speaking about this error : 
`
(04:23:45) ERROR: C:/b/zfqvonkt/external/com_github_google_googletest/BUILD.bazel:80:11: Compiling googletest/src/gtest-filepath.cc failed: undeclared inclusion(s) in rule '@com_github_google_googletest//:gtest':
--
  | this rule is missing dependency declarations for the following files included by 'googletest/src/gtest-filepath.cc':
  | 'C:/Program Files/LLVM/lib/clang/16/include/vadefs.h'
  | 'C:/Program Files/LLVM/lib/clang/16/include/stdint.h'
  | 'C:/Program Files/LLVM/lib/clang/16/include/limits.h'
  | 'C:/Program Files/LLVM/lib/clang/16/include/stddef.h'
  | 'C:/Program Files/LLVM/lib/clang/16/include/__stddef_max_align_t.h'
  | 'C:/Program Files/LLVM/lib/clang/16/include/stddef.h'
  | 'C:/Program Files/LLVM/lib/clang/16/include/float.h'
  | 'C:/Program Files/LLVM/lib/clang/16/include/stddef.h'
`

We experienced a similar issue in one of our project (@ E-Scopics) when I tried using a more recent LLVM toolchain.
If I remember correctly, it's because some version of bazel are not working with the latest llvm/clang. 

I don't know how the bazel buildkite works, has there been any change in Bazel version of Clang version ?

Using the latest Bazel release should fix the problem.  I don't think it has anything to do with glog itself.

**Comment by drigz** [comment]
Thanks for taking a look!

@sgowroji reported something similar recently, which was an internal issue. https://github.com/google/glog/issues/938

**Comment by sergiud** [comment]
Thanks @skeptic-monkey.

I wondering whether it is possible to pin a specific Bazel version to avoid such problems in the future. Buildkite documentation does not seem provide any pointers.

**Comment by sergiud** [comment]
I'm closing the issue since Bazel CI is no longer failing.
